version: '3.7'

services:
  aireading:
    build: ./aireading
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --forwarded-allow-ips=* --proxy-headers
    volumes:
      - ./aireading/:/app/
    environment:
      - OPENAI_API_KEY=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
  
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - aireading
    # logging:
    #   driver: none
